services:
  - type: web
    name: chitfund-pro
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: oregon
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
              value: "true"
      - key: APP_KEY
              value: base64:dGhpc2lzYTNydHdvd2J5dGVzZW5jcnlwdGlvbmtleQ==
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /var/www/html/database/database.sqlite
      - key: SESSION_DRIVER
        value: cookie
      - key: CACHE_STORE
        value: array
